/*
 * generated by Xtext
 */
package eu.indenica.config.runtime;

import org.eclipse.xtext.scoping.IScopeProvider;

import eu.indenica.config.runtime.scoping.RuntimeScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RuntimeRuntimeModule extends eu.indenica.config.runtime.AbstractRuntimeRuntimeModule {
	/* (non-Javadoc)
	 * @see eu.indenica.config.runtime.AbstractRuntimeRuntimeModule#bindIScopeProvider()
	 */
	@Override
	public Class<? extends IScopeProvider> bindIScopeProvider() {
		return RuntimeScopeProvider.class;
	}
}
