/*
* generated by Xtext
*/
package eu.indenica.config.runtime.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class RuntimeOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
