/*
 * generated by Xtext
 */
package eu.indenica.config.runtime.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class RuntimeUiModule extends eu.indenica.config.runtime.ui.AbstractRuntimeUiModule {
	public RuntimeUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
