/*
 * generated by Xtext
 */
package eu.indenica.config.runtime.scoping;

import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.Scopes;
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;

import eu.indenica.config.runtime.runtime.EventEmissionDeclaration;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping on
 * how and when to use it
 * 
 */
public class RuntimeScopeProvider extends AbstractDeclarativeScopeProvider {
	IScope scope_EventAttribute(EventEmissionDeclaration ctx, EReference ref) {
		return Scopes.scopeFor(ctx.getEvent().getAttributes());
	}
}
