/*
* generated by Xtext
*/
package eu.indenica.config.runtime.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class RuntimeProposalProvider extends AbstractRuntimeProposalProvider {

}
